### ISSUE TITLE
Implement `parseToStream`

### ISSUE THREAD

**Issue by burakkose** [dylemma/xml-spac#16]
I have not checked the implementation, but I was wondering about transformer API. There is `parseToList`, shall we consider to add `parseToStream` or something lazy for each element. 

Especially, it can be really handy for data ingestion.

**Comment by dylemma** [comment]
The intent of the "parse" methods is to consume the whole stream (or at least up until the consumer says it's done) into some useful value. To return a lazy collection, you'd want to avoid doing any parsing steps until you attempt to evaluate the next element of your collection.

Conceptually, it should be possible to define something like
```scala
def makeIterator[Src, In, Out](
  source: Src, 
  t: Transformer[In, Out]
)(cl: ConsumableLike[Src, In]): Iterator[Out]
```

but right now the `ConsumableLike` abstraction (i.e. how I'm modelling a stream "source") only exposes a "push-like" (i.e. foreach-ish) interface. I'll definitely keep this in mind as I work on v0.6

**Comment by dylemma** [comment]
0.6 is out, so you can use `Transformer.transform(source)` to get an iterator.
