### ISSUE TITLE
Scala 2.13 Support

### ISSUE THREAD

**Issue by kryptt** [dylemma/xml-spac#22]
Hi, I locally built this to support scala 2.13, are you interested in a pull request for this?

**Comment by dylemma** [comment]
Sure, as long as you stick to the same general code style, I'll merge your PR.

**Comment by dylemma** [comment]
Looks like scalamock-scalatest-support doesn't have a 2.13 build yet, so the "xml" project's tests won't compile on 2.13. I'll need to find a way around that.

**Comment by dylemma** [comment]
0.7 is released! Closing this.

**Comment by kryptt** [comment]
:+1: sorry  I never got do a PR for it. it was too flimsy anyway
