### ISSUE TITLE
How to get List of Try?

### ISSUE THREAD

**Issue by kyrick** [dylemma/xml-spac#23]
Hello I'm trying to parse a list of xml blocks. The structure is something like this:
```xml
<THINGS>
   <THING>
     <DETAILS>
     <ID>1234</ID>
     <FOO>bar</FOO>
     </DETAILS>
    </THING>
    <THING>
     <DETAILS>
     <FOO>bar</FOO>
     </DETAILS>
    </THING>
</THINGS>
```

My parser for this looks something like:
```scala
object ThingParser {
  case class Thing(id: String, foo: String)

  implicit val ThingParser: XMLParser[Thing] = (
    XMLSplitter(* \ "DETAILS" \ "ID").first.asText and 
      XMLSplitter(* \ "DETAILS" \ "FOO").first.asText
    ).as(Thing)

  def parseXmlStringToList(xmlSource: String) = {
    val thingTransformer = XMLSplitter("THINGS" \ "THING").as[Thing]
    val consumer = thingTransformer.wrapSafe.parseToList
    consumer.parse(xmlSource)
  }
}
```

The issue I'm encountering -- I'm trying to parse THING to a list of case classes like `case class Thing(id: String)`. The problem is, if one thing is missing the ID then the XMLSplitter fails and the entire parse fails. What I want is something more like `List[Try[Thing]]`. But wrapSafe still throws an exception. 

Is there an easy way to do this? Do I need to write a custom handler?

**Comment by dylemma** [comment]
Hi and thanks for your interest in my library!

You can use `.wrapSafe` on the parser instead of the transformer to get what you're looking for:

```scala
XMLSplitter("THINGS" \ "THING").as(ThingParser.wrapSafe).parseToList.parse(xmlSource)
// List(Success(Thing(1234,bar)), Failure(NoSuchElementException))
```

Not sure why it wasn't working if you `.wrapSafe` the transformer - that is probably a bug, so I'll leave this issue open as a reminder to myself.

As a side note, you can use `.firstOption` to avoid a NoSuchElementException being thrown in cases like this, and not have to deal with `Try` and `wrapSafe`.

**Comment by dylemma** [comment]
Actually I'm thinking that Transformer simply shouldn't *have* a `wrapSafe` method. 

Thinking about how to implement one, it would have to be a different wrapper implementation depending on the transformer. For transformers generated from a Splitter+Parser combo, you could `.wrapSafe` the Parser as I suggested in my last comment. But for other things it's not clear what the scope of the wrapSafe is... 

Let's say you have a `transformer.map(f).wrapSafe`. Does the wrapSafe only protect the execution of the `f` function inside the map operation? Does it try to protect from errors that happen upstream? How would it do so? How does it behave when an error is encountered (end the stream, somehow recover)? 

It's too many variables for an in-library implementation to make a good guess at. I'd rather leave that logic in the hands of the library user.
